#!/bin/bash

echo process count:
ps axu | cut -d ' ' -f 1 |sort |uniq -c |sort -rg |egrep -v 'USER|root' |head -10
echo

echo 'Total ram per user (top 10):'
(echo "user rss(KiB) vmem(KiB)";
 for user in $(ps axk ruser  -o ruser= |uniq); do
   echo $user $(ps -U $user --no-headers -o rss,vsz \
     | awk '{rss+=$1; vmem+=$2} END{print rss" "vmem}')
 done | sort -rgk 2
) | column -t | head -11
echo

echo shell count:
w | cut -d ' ' -f 1 |sort |uniq -c |sort -rg |grep -v USER |head -5
echo

if [ "$1" == "" ]
then
  DELAY=2
else
  DELAY=$1
fi

echo Top two CPU hogs:
top -b -d$DELAY -n2 |grep -A 2 USER |tail -2 |awk '{ print $2 }'
